add attribute based formatting for sysconfig(defaults) and db config update init files with upstream files from mongodb/mongo

diff --git a/templates/default/debian-mongodb.init.erb b/templates/default/debian-mongodb.init.erb
--- a/templates/default/debian-mongodb.init.erb
+++ b/templates/default/debian-mongodb.init.erb
@@ -1,13 +1,4 @@
-#!/bin/sh
-#
-### BEGIN INIT INFO
-# Provides:          <%= @provides %>
-# Required-Start:    $local_fs $remote_fs
-# Required-Stop:     $local_fs $remote_fs
-# Default-Start:
-# Default-Stop:
-# Short-Description: Start/stop mongodb <%= @provides %>
-### END INIT INFO
+#!/bin/bash
 #
 # init.d script with LSB support.
 #
@@ -30,31 +21,65 @@
 # not, write to the Free Software Foundation, Inc., 59 Temple Place,
 # Suite 330, Boston, MA 02111-1307 USA
 #
-
+### BEGIN INIT INFO
+# Provides:          <%= @provides %>
+# Required-Start:    $network $local_fs $remote_fs
+# Required-Stop:     $network $local_fs $remote_fs
+# Should-Start:      $named
+# Should-Stop:
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Start/stop <%= @provides %> An object/document-origented database
+# Description:       MongoDB is a high-performance, open source, schema-free
+#                    document-oriented  data store that's easy to deploy, manage
+#                    and use. It's network accessible, written in C++ and offers
+#                    the following features:
+#
+#                       * Collection oriented storage - easy storage of object-
+#                         style data
+#                       * Full index support, including on inner objects
+#                       * Query profiling
+#                       * Replication and fail-over support
+#                       * Efficient storage of binary data including large
+#                         objects (e.g. videos)
+#                       * Auto-sharding for cloud-level scalability (Q209)
+#
+#                    High performance, scalability, and reasonable depth of
+#                    functionality are the goals for the project.
+### END INIT INFO
+#
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DESC=database
-DAEMON=/usr/bin/mongod
-DAEMON_OPTS="--config /etc/mongodb.conf"
-
+PIDFILE=/var/run/$NAME.pid
 ENABLE_MONGODB=yes
+SYSCONFIG=<%= node['mongodb']['sysconfig_file'] %>
 
 NAME=<%= @provides %>
 
-<% if %w{ ubuntu debian }.include? node.platform -%>
-ulimit -f <%= node.mongodb.ulimit.file_size %>
-ulimit -t <%= node.mongodb.ulimit.cpu_time %>
-ulimit -v <%= node.mongodb.ulimit.virtual_memory %>
-ulimit -n <%= node.mongodb.ulimit.open_files %>
-ulimit -m <%= node.mongodb.ulimit.memory_size %>
-ulimit -u <%= node.mongodb.ulimit.processes %>
-<% end -%>
+# this should get removed at some point for more shell agnostic init script
+ulimit -f <%= node.mongodb.ulimit.fsize %>
+ulimit -t <%= node.mongodb.ulimit.cpu %>
+ulimit -v <%= node.mongodb.ulimit.as %>
+ulimit -n <%= node.mongodb.ulimit.nofile %>
+ulimit -m <%= node.mongodb.ulimit.rss %>
+ulimit -u <%= node.mongodb.ulimit.nproc %>
 
 # Include mongodb defaults if available
-if [ -f /etc/default/$NAME ] ; then
-	. /etc/default/$NAME
+if [ -f $SYSCONFIG ] ; then
+    . $SYSCONFIG
 fi
 
-PIDFILE=/var/run/$NAME.pid
+# Handle NUMA access to CPUs (SERVER-3574)
+# This verifies the existence of numactl as well as testing that the command works
+NUMACTL_ARGS="--interleave=all"
+if which numactl >/dev/null 2>/dev/null && numactl $NUMACTL_ARGS ls / >/dev/null 2>/dev/null
+then
+    NUMACTL="`which numactl` -- $NUMACTL_ARGS"
+    DAEMON_OPTS="$DAEMON_OPTS"
+else
+    NUMACTL=""
+    DAEMON_OPTS="-- $DAEMON_OPTS"
+fi
 
 if test ! -x $DAEMON; then
     echo "Could not find $DAEMON"
@@ -113,9 +138,9 @@ start_server() {
 # Start the process using the wrapper
             start-stop-daemon --background --start --quiet --pidfile $PIDFILE \
                         --make-pidfile --chuid $DAEMONUSER \
-                        --exec $DAEMON -- $DAEMON_OPTS
+                        --exec $NUMACTL $DAEMON $DAEMON_OPTS
             errcode=$?
-	return $errcode
+    return $errcode
 }
 
 stop_server() {
@@ -125,32 +150,32 @@ stop_server() {
                         --user $DAEMONUSER \
                         --exec $DAEMON
             errcode=$?
-	return $errcode
+    return $errcode
 }
 
 force_stop() {
 # Force the process to die killing it manually
-	[ ! -e "$PIDFILE" ] && return
-	if running ; then
-		kill -15 $pid
-	# Is it really dead?
-		sleep "$DIETIME"s
-		if running ; then
-			kill -9 $pid
-			sleep "$DIETIME"s
-			if running ; then
-				echo "Cannot kill $NAME (pid=$pid)!"
-				exit 1
-			fi
-		fi
-	fi
-	rm -f $PIDFILE
+    [ ! -e "$PIDFILE" ] && return
+    if running ; then
+        kill -15 $pid
+    # Is it really dead?
+        sleep "$DIETIME"s
+        if running ; then
+            kill -9 $pid
+            sleep "$DIETIME"s
+            if running ; then
+                echo "Cannot kill $NAME (pid=$pid)!"
+                exit 1
+            fi
+        fi
+    fi
+    rm -f $PIDFILE
 }
 
 
 case "$1" in
   start)
-	log_daemon_msg "Starting $DESC" "$NAME"
+    log_daemon_msg "Starting $DESC" "$NAME"
         # Check if it's running first
         if running ;  then
             log_progress_msg "apparently already running"
@@ -161,7 +186,7 @@ case "$1" in
             # NOTE: Some servers might die some time after they start,
             # this code will detect this issue if STARTTIME is set
             # to a reasonable value
-            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time 
+            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
             if  running ;  then
                 # It's ok, the server started and is running
                 log_end_msg 0
@@ -173,12 +198,12 @@ case "$1" in
             # Either we could not start it
             log_end_msg 1
         fi
-	;;
+    ;;
   stop)
         log_daemon_msg "Stopping $DESC" "$NAME"
         if running ; then
             # Only stop the server if we see it running
-			errcode=0
+            errcode=0
             stop_server || errcode=$?
             log_end_msg $errcode
         else
@@ -194,14 +219,14 @@ case "$1" in
         if running; then
             # If it's still running try to kill it more forcefully
             log_daemon_msg "Stopping (force) $DESC" "$NAME"
-			errcode=0
+            errcode=0
             force_stop || errcode=$?
             log_end_msg $errcode
         fi
-	;;
+    ;;
   restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
-		errcode=0
+        errcode=0
         stop_server || errcode=$?
         # Wait some sensible amount, some server need this
         [ -n "$DIETIME" ] && sleep $DIETIME
@@ -209,7 +234,7 @@ case "$1" in
         [ -n "$STARTTIME" ] && sleep $STARTTIME
         running || errcode=$?
         log_end_msg $errcode
-	;;
+    ;;
   status)
 
         log_daemon_msg "Checking status of $DESC" "$NAME"
@@ -229,10 +254,10 @@ case "$1" in
         ;;
 
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+    N=/etc/init.d/$NAME
+    echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+    exit 1
+    ;;
 esac
 
 exit 0
